name: image_picker_plus
description: Customization of the gallery display or even camera and video.
version: 0.5.9
homepage: https://github.com/AhmedAbdoElhawary/image_picker_plus.git

environment:
  sdk: '>=2.17.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.0.0-dev.5
  shimmer: ^3.0.0
  camera: ^0.10.5+2
  image: ^4.0.17
  video_player: ^2.7.0
  image_picker: ^1.0.1
  insta_assets_crop: ^0.0.3
  cached_memory_image: ^1.5.0
  intl: any
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
