name: shared
description: A package that manages shared data.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  app_ui:
    path: ../app_ui
  bloc_concurrency: ^0.2.4
  blurhash: ^1.1.1
  dio: ^5.4.0
  env:
    path: ../env
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  freezed_annotation: ^2.4.1
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  image_picker_plus:
    path: ../image_picker_plus
  image_size_getter: ^2.1.2
  # images_picker: ^1.2.11
  insta_assets_picker: ^2.2.1
  insta_blocks:
    path: ../insta_blocks
  intl: ">=0.18.0 <0.19.0"
  jiffy: ">=6.2.1 <6.2.2"
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  meta: ">=1.10.0 <=1.12.0"
  mime: ^1.0.4
  ogp_data_extract: ^0.1.4
  powersync: ^1.1.0
  stream_transform: ^2.1.0
  user_repository:
    path: ../user_repository
  uuid: ^4.3.3
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
