name: supabase_authentication_client
description: A Supabase implementation of the authentication client interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ^3.22.0

dependencies:
  authentication_client:
    path: ../authentication_client
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  powersync_repository:
    path: ../../powersync_repository
  shared:
    path: ../../shared
  supabase_flutter: ^2.2.0
  token_storage:
    path: ../token_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
