name: user_repository
description: A package that manages user flow.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  database_client:
    path: ../database_client
  flutter:
    sdk: flutter
  powersync_repository:
    path: ../powersync_repository
  rxdart: ^0.27.7
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
