name: insta_blocks
description: Reusable Instagram Blocks for Flutter Instagram offline-first clone
  Application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  meta: ">=1.10.0 <1.12.0"
  shared:
    path: ../shared
  user_repository:
    path: ../user_repository

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
