name: flutter_instagram_offline_first_clone
description: A complete offline-first Flutter Instagram clone with Supabase and PowerSync.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animations: ^2.0.11
  app_ui:
    path: packages/app_ui
  async: ^2.11.0
  bloc: ^8.1.4
  cached_memory_image: ^1.5.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chats_repository:
    path: packages/chats_repository
  collection: ^1.18.0
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.1
  firebase_core: ">=2.25.0 <3.0.0"
  firebase_messaging: ">=14.7.10 <15.0.0"
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  firebase_remote_config_repository:
    path: packages/firebase_remote_config_repository
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ">=0.6.20 <0.7.0"
  flutter_portal: ^1.1.4
  flutter_staggered_grid_view: ^0.7.0
  form_fields:
    path: packages/form_fields
  get_it: ^7.6.7
  go_router: ^13.2.1
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  insta_blocks:
    path: packages/insta_blocks
  instagram_blocks_ui:
    path: packages/instagram_blocks_ui
  intl: ">=0.18.0 <0.19.0"
  inview_notifier_list:
    git: https://github.com/Gambley1/inview_notifier_list
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  notifications_repository:
    path: packages/notifications_repository
  ogp_data_extract: ^0.1.4
  path_provider: ^2.1.2
  persistent_storage:
    path: packages/storage/persistent_storage
  posts_repository:
    path: packages/posts_repository
  powersync_repository:
    path: packages/powersync_repository
  scrollable_positioned_list: ^0.3.8
  search_repository:
    path: packages/search_repository
  shared:
    path: packages/shared
  shimmer: ^3.0.0
  slang: ^3.30.1
  slang_flutter: ^3.29.0
  sliver_tools: ^0.2.12
  sprung: ^3.0.1
  stories_editor:
    path: packages/stories_editor
  stories_repository:
    path: packages/stories_repository
  story_view: ^0.16.5
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  timeago: ^3.6.1
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher: ^6.2.5
  user_repository:
    path: packages/user_repository
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  flutter_gen: ^5.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  slang_build_runner: ^3.30.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
