name: notifications_client
description: A Generic Notifications Client Interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
