name: firebase_notifications_client
description: A Firebase Cloud Messaging notifications client.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ^3.19.3

dependencies:
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  notifications_client:
    path: ../notifications_client
  shared:
    path: ../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
