name: firebase_remote_config_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ^3.22.0

dependencies:
  firebase_remote_config: ^5.1.1
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0
