name: stories_repository
description: A repository that manages stories data flow.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  database_client:
    path: ../database_client
  equatable: ^2.0.5
  rxdart: ^0.27.7
  shared:
    path: ../shared
  storage:
    path: ../storage/storage
  user_repository:
    path: ../user_repository

dev_dependencies:
  mocktail: ^1.0.2
  test: ^1.25.1
  very_good_analysis: ^5.1.0
