name: database_client
description: A package that manages application database workflow.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  dio: ^5.4.0
  env:
    path: ../env
  flutter:
    sdk: flutter
  jiffy: ">=6.2.1 <6.2.2"
  powersync_repository:
    path: ../powersync_repository
  shared:
    path: ../shared
  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0
